Mixpanel sdk
Montreal-Analytics/dbt-gloss-deprecated pull request #10
Opened 2022-10-07 14:10 UTC by dangkv

2022-10-13 11:19 UTC, JFrackson requested changes
A few requested changes just looking at how we might best implement this for scalability

2022-10-13 11:19 UTC, JFrackson commented on dbt_gloss/check_model_has_description.py
> +def tracking(manifest, hook_metadata, runtime, script_args):
Having this as a function in the hook file feels not very sustainable. Can we move any of this functionality into the tracking.py file? Notably the hook_name parsing or the disable_tracking part?

2022-10-13 11:19 UTC, JFrackson commented on dbt_gloss/check_model_has_description.py
> +        mixpanel = dbtGlossTracking(disable_tracking)
naming this `mixpanel` is a bit confusing. Maybe we just call it something like `tracker` so that it will look like `tracker.track_hook_event`. That way nobody will think the mixpanel dependency is being used in this file directly

2022-10-13 11:19 UTC, JFrackson commented on dbt_gloss/check_model_has_description.py
> +        'object_count': len(list(models))+1,
Just thinking about how we might do this for all hooks. Maybe we do this in the tracking.py file and just parse it from the manifest?

2022-10-13 11:19 UTC, JFrackson commented on tests/conftest.py
> +        "project_id":"project_id",
maybe just for ease of parsing in mixpanel we can prefix some of these with `test_` to make it `test_project_id` and `test_user_id`

2022-10-13 14:46 UTC, dangkv commented on dbt_gloss/check_model_has_description.py
> +        'object_count': len(list(models))+1,
hmm this will be tough cause all this information is related to the hook itself

`status_code`: success or fail status of the hook
`object_count`: the count of `sql` or `yml` the hook scanned
`error_count`: the count of failed objects determined by the hook

2022-10-13 15:13 UTC, dangkv commented on tests/conftest.py
> +        "project_id":"project_id",
done

2022-10-13 17:12 UTC, dangkv commented on dbt_gloss/check_model_has_description.py
> +    try:
Bring the try except in the tracking.py file

2022-10-13 17:17 UTC, dangkv commented on dbt_gloss/check_model_has_description.py
> +        'object_count': len(list(models))+1,
Change variable name from `metadata` to `hook_properies`

2022-10-13 17:42 UTC, dangkv commented on dbt_gloss/check_model_has_description.py
> +        runtime=end_time - start_time,
change variable name from `runtime` to `execution time`

2022-10-13 17:44 UTC, dangkv commented on dbt_gloss/check_model_has_description.py
> +        'object_count': len(list(models))+1,
remove error count and obj count

2022-11-21 15:29 UTC, JFrackson reviewed
One comment about the implementation but otherwise it looks good. Also, we should add a comment in the README about this. I know you have something similar in another PR that could be reworked. How about we review the technical solution here and then merge that documentation PR into this one before fully validating and merging

2022-11-21 15:29 UTC, JFrackson commented on tests/unit/test_check_model_has_description.py
> +    (["aa/bb/with_description.sql", '--is_test'], True, True, 0),
Would it be possible to create a dev config file that disables tracking and thus makes this `--is-test` not necessary?

2022-11-21 15:36 UTC, dangkv commented on tests/unit/test_check_model_has_description.py
> +    (["aa/bb/with_description.sql", '--is_test'], True, True, 0),
Not sure if I understand the question. 
The `--is-test flag` is to flag the tracking event as a test event

Im currently working on a yaml config file to disable tracking, so you don't have to write `--disable-tracking` for each hook

2022-11-21 15:37 UTC, dangkv commented on tests/unit/test_check_model_has_description.py
> +    (["aa/bb/with_description.sql", '--is_test'], True, True, 0),
![image](https://user-images.githubusercontent.com/60619082/203095616-c8ac3929-2c5a-43c6-a0ab-b80fb188e759.png)

2022-11-21 22:11 UTC, dangkv commented on tests/unit/test_check_model_has_description.py
> +    (["aa/bb/with_description.sql", '--is_test'], True, True, 0),
Did you mean having a config option that globally marks all runs as testing?
like:
```
disable-tracking: False
is_test: True
```
`.dbt-gloss.yaml`

2022-11-24 14:27 UTC, JFrackson commented on tests/unit/test_check_model_has_description.py
> +    (["aa/bb/with_description.sql", '--is_test'], True, True, 0),
Yeah I thought about this again and I think based on what we said about having two accounts (one for dev and one for prod) this may not really be needed as a tracking argument anymore (e.g. in dev we won't care to filter out is_pytest data). 

We would use is_pytest to determine which token to use, but not actually pass it to mixpanel. Does that make more sense? I.e. dev account would always have is_pytest==true and prod would always have is_ptyest==false.

2022-11-24 22:17 UTC, dangkv commented on tests/unit/test_check_model_has_description.py
> +    (["aa/bb/with_description.sql", '--is_test'], True, True, 0),
Ok so the recent implementation has 2 options to flag if a run is a test. You can either use the `--is_test` flag as an arg for a single hook or put `is_test: True` in the `.dbt-gloss.yaml` to indicate all runs are tests

2022-11-24 22:41 UTC, dangkv commented on dbt_gloss/utils.py
> +def add_default_args(parser: argparse.ArgumentParser) -> None:
@JFrackson 

This function bundles 4 common `add_args` functions to reduce bloat.

2022-11-24 22:42 UTC, dangkv commented on dbt_gloss/tracking.py
> +    def _get_mixpanel_env_token(self) -> str:
@JFrackson 
This function handles the dev and prod tokens for mixpanel

2022-11-25 12:54 UTC, dangkv commented on dbt_gloss/utils.py
> +def check_yml_version(file_path, yaml_dct) -> None:
yml version control feature

2022-12-05 13:09 UTC, JFrackson approved these changes
This looks good to me! Maybe we can clean up the body of the PR or even open a new PR for commit history cleanliness and then get some of the team members at MTLA to try this out before merging?

2023-06-05 13:35 UTC, JFrackson commented
Closing this as we've merged this into [dbt-checkpoint](https://github.com/dbt-checkpoint/dbt-checkpoint) successfully!

2023-06-05 13:35 UTC, closed without merging