Fix/check script has no table missing whitespaces
Montreal-Analytics/dbt-gloss-deprecated pull request #5
Opened 2022-09-22 19:56 UTC by pantonacci

Fixed an issue where missing whitespaces in the dbt `{{ ref }}` function caused an error in the `check-script-has-no-table-name` hook for the ticket: https://app.clickup.com/t/29p4yb2 which addresses the issue raised in: https://github.com/offbi/pre-commit-dbt/issues/44 and added a test to make sure that it would pass.

This should also solve the other issue raised by the ticket: https://app.clickup.com/t/29p4yau

2022-09-26 12:22 UTC, JFrackson requested changes
I think you have the right approach but you could leverage regex in a way that's more similar to the other case. Let me know if that's unclear!

2022-09-26 12:22 UTC, JFrackson commented on pre_commit_dbt/check_script_has_no_table_name.py
> +    return re.sub(REGEX_PARENTHESIS, r" \1 ", sql).replace('{{','{{ ').replace('}}',' }}')
I think this is a good approach, but based on how the REGEX_PARANTHESIS pattern is set I wonder if it would make more sense to make a second function called `add_space to_braces()` and to do the same task but with `{` instead of `(`. Does that make sense? I think setting another REGEX_BRACES variable as `([\{\}])` could work but you might want to test that out more

2022-10-05 14:36 UTC, pantonacci commented on pre_commit_dbt/check_script_has_no_table_name.py
> +    return re.sub(REGEX_PARENTHESIS, r" \1 ", sql).replace('{{','{{ ').replace('}}',' }}')
Updated, but I needed to add another ignore word for single curly braces!

2022-10-31 14:36 UTC, JFrackson approved these changes
lgtm

2022-11-03 18:03 UTC, merged